"""Render docs/machine.md from results/machine.json.

Keeps the prose in the docs traceable to a committed measurement rather than to
someone's memory of a spec sheet. Run after `python bench/machine.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def main() -> None:
    data = json.loads((REPO / "results" / "machine.json").read_text())
    tc = data["toolchain"]
    out: list[str] = []
    w = out.append

    w("# Machine and environment\n")
    w("Generated by `scripts/render_machine.py` from `results/machine.json`,")
    w("which is produced by `python bench/machine.py`. Every performance number")
    w("in this repository is measured on this machine with this software.\n")

    w("## GPUs\n")
    w("| | " + " | ".join(f"GPU {i}" for i in data["devices"]) + " |")
    w("|---|" + "---|" * len(data["devices"]))
    rows = [
        ("Name", lambda d: d["properties"]["name"]),
        ("Compute capability", lambda d: d["properties"]["compute_capability"]),
        ("SMs", lambda d: str(d["properties"]["multi_processor_count"])),
        ("Memory", lambda d: f"{d['properties']['total_memory_bytes'] / 2**30:.0f} GiB"),
        ("L2 cache", lambda d: f"{d['properties']['l2_cache_size_bytes'] / 2**20:.0f} MiB"),
        (
            "Shared mem / block (opt-in)",
            lambda d: f"{d['properties']['shared_memory_per_block_optin_bytes'] / 1024:.0f} KiB",
        ),
        (
            "DRAM copy (measured)",
            lambda d: f"{d['bandwidth_dram']['copy']['gbytes_per_s']:.0f} GB/s",
        ),
        (
            "DRAM read (measured)",
            lambda d: f"{d['bandwidth_dram']['read']['gbytes_per_s']:.0f} GB/s",
        ),
        (
            "L2 peak copy (measured)",
            lambda d: f"{d['bandwidth_sweep']['l2_peak_gbytes_per_s']:.0f} GB/s",
        ),
        (
            "BF16 matmul 4096 (measured)",
            lambda d: f"{d['matmul']['bf16_4096']['tflop_per_s']:.0f} TFLOP/s",
        ),
        (
            "Triton launch overhead",
            lambda d: f"{d['launch_overhead']['triton_empty_us']:.1f} us",
        ),
        (
            "CUDA-graph replay overhead",
            lambda d: f"{d['launch_overhead'].get('torch_tiny_op_cudagraph_us', float('nan')):.2f} us",
        ),
    ]
    for label, fn in rows:
        w(f"| {label} | " + " | ".join(fn(d) for d in data["devices"].values()) + " |")

    theo = data.get("theoretical_dram_bandwidth") or []
    if theo:
        t = theo[0]
        d0 = next(iter(data["devices"].values()))
        meas = d0["bandwidth_dram"]["read"]["gbytes_per_s"]
        w(
            f"\nTheoretical DRAM bandwidth is {t['theoretical_gbytes_per_s']:.0f} GB/s "
            f"({t['memory_clock_mhz']:.0f} MHz x 2 x {t['assumed_bus_width_bits']}-bit). "
            f"The measured read figure is {100 * meas / t['theoretical_gbytes_per_s']:.0f}% of that. "
            "Nothing in this repository divides by the theoretical number; efficiency is always "
            "quoted against the measured one.\n"
        )

    w("## The bandwidth curve\n")
    w("Copy bandwidth against working-set size, with launch overhead amortized")
    w("equally at every size. The L2 plateau is the reason a two-pass formulation")
    w("of the operator is worth considering: a token tile whose sources stay")
    w("resident between passes pays L2 bandwidth for the second pass, not DRAM.\n")
    d0 = next(iter(data["devices"].values()))
    w("| Working set | Copy GB/s |")
    w("|---|---|")
    for pt in d0["bandwidth_sweep"]["curve"]:
        w(f"| {pt['mib']} MiB | {pt['copy_gbytes_per_s']:.0f} |")
    sw = d0["bandwidth_sweep"]
    w(
        f"\nL2 peak / DRAM plateau = "
        f"{sw['l2_peak_gbytes_per_s'] / sw['dram_plateau_gbytes_per_s']:.2f}x.\n"
    )

    w("## Interconnect\n")
    p = data["p2p"]
    w(f"- Peer access 0->1: `{p.get('can_access_peer_0_1')}`, 1->0: `{p.get('can_access_peer_1_0')}`")
    w(f"- Measured device-to-device copy: {p['d2d_0to1']['gbytes_per_s']:.1f} GB/s")
    w(f"- Measured host-to-device (pinned): {p['h2d_pinned']['gbytes_per_s']:.1f} GB/s\n")
    w("Peer access is available but runs over PCIe. There is no NVLink between")
    w("these cards, so any two-GPU work in this project treats the link as slow")
    w("and avoids designs that need frequent cross-device traffic.\n")

    w("## Toolchain\n")
    for label, key in [
        ("Python", "python"), ("PyTorch", "torch"), ("PyTorch CUDA", "torch_cuda"),
        ("Triton", "triton"), ("nvcc", "nvcc_version"), ("Platform", "platform"),
    ]:
        if tc.get(key):
            w(f"- {label}: `{tc[key]}`")
    w(f"- PyTorch arch list: `{', '.join(tc.get('torch_arch_list', []))}`")
    w(f"- nvcc supports `sm_120`: `{tc.get('nvcc_supports_sm120')}`\n")

    w("### Profiling constraints\n")
    ncu = data.get("ncu", {})
    if ncu.get("permission_denied"):
        w("**Nsight Compute cannot be used on this host.** `ncu` is installed and")
        w("runs, but collecting hardware counters fails with `ERR_NVGPUCTRPERM`:")
        w("the driver restricts performance counters to administrators")
        w("(`NVreg_RestrictProfilingToAdminUsers`). Changing that is a host-wide")
        w("modification, so this project does not do it, and no claim here rests on")
        w("an `ncu` counter.\n")
        w("The substitutes used instead:\n")
        w("- **Nsight Systems** (`nsys`) works without special privileges, and gives")
        w("  kernel timelines, launch counts and durations.")
        w("- **`torch.profiler`** gives per-kernel CUDA time and launch counts.")
        w("- **Analytical roofline.** This operator is memory-bound by roughly two")
        w("  orders of magnitude, so achieved bandwidth derived from measured")
        w("  latency and an exact byte count answers most of what `ncu` would.\n")
    else:
        w("Nsight Compute counter collection is permitted on this host.\n")

    dest = REPO / "docs" / "machine.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(out) + "\n")
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
