"""Render docs/model.md from results/model_*.json."""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def main() -> None:
    src = next(iter(sorted((REPO / "results").glob("model_*.json"))), None)
    if src is None:
        raise SystemExit("no results/model_*.json; run bench/bench_model.py first")
    d = json.loads(src.read_text())
    env = d.get("environment", {})
    variants = d["variants"]
    by_name = {v["variant"]: v for v in variants}
    attribution = {a["variant"]: a for a in d.get("attribution", [])}
    cfg = d.get("config", {})

    out: list[str] = []
    w = out.append
    w("# End-to-end: Block AttnRes in a 1.3B decoder\n")
    w("Generated by `scripts/summarize_model.py` from")
    w(f"`results/{src.name}`. Reproduce with `python bench/bench_model.py`.\n")
    w("The operator microbenchmark answers how fast the kernel is. This answers the")
    w("question that actually matters: **how much of a training step does the residual")
    w("mechanism cost, and how much of that does fusing it remove?**\n")
    w(f"{env.get('device_name', 'unknown device')}, {d.get('dtype')}, "
      f"batch {d.get('batch')} x seq {d.get('seq')}. "
      f"{cfg.get('n_layers')} layers ({2 * cfg.get('n_layers', 0)} sublayers), "
      f"d_model {cfg.get('d_model')}, d_ff {cfg.get('d_ff')}, "
      f"{cfg.get('n_blocks')} AttnRes blocks, vocab {cfg.get('vocab_size')}.\n")
    w("`standard` is an ordinary PreNorm residual and is the control. The two AttnRes")
    w("modes differ *only* in which operator implements the mechanism: same weights,")
    w("same data path, same sequence attention, and parameter counts equal by")
    w("construction and asserted in `tests/test_model.py`. `stack` builds the source")
    w("tensor with `torch.stack` at every site, as the paper's pseudocode does; `arena`")
    w("writes each source once into a preallocated buffer.\n")

    w("| variant | params | fwd ms | bwd ms | step ms | tokens/s | peak GiB |")
    w("|---|---|---|---|---|---|---|")
    for v in variants:
        b = "**" if v["variant"] == "switchyard/arena" else ""
        w(f"| {b}{v['variant']}{b} | {v['params']['total'] / 1e9:.3f}B | "
          f"{v['forward']['median_ms']:.2f} | {v['backward_only_ms']:.2f} | "
          f"{b}{v['step']['median_ms']:.2f}{b} | {v['tokens_per_second']:.0f} | "
          f"{v['peak_memory_bytes'] / 2**30:.2f} |")

    w("\n## What the mechanism costs\n")
    w("Two independent estimates. **Control difference** subtracts the standard-residual")
    w("step time and so captures everything the mechanism adds, plumbing included.")
    w("**Profiler** attributes time to the operator's own `record_function` regions,")
    w("which is narrower and misses backward work that autograd spreads across generic")
    w("nodes -- for `attnres/stack` it cannot be attributed at all, which is itself why")
    w("the control difference is the number quoted.\n")
    w("| variant | added ms | % of step (control diff) | % of step (profiler) |")
    w("|---|---|---|---|")
    for v in variants:
        if v["residual"] == "standard":
            continue
        a = attribution.get(v["variant"], {})
        prof = a.get("profiler_share_pct")
        w(f"| {v['variant']} | {a.get('step_delta_ms', float('nan')):.1f} | "
          f"{a.get('step_share_pct', float('nan')):.1f}% | "
          f"{f'{prof:.1f}%' if prof is not None else 'not attributable'} |")

    base = by_name["standard"]
    fw = by_name.get("attnres/arena")
    ours = by_name.get("switchyard/arena")
    stack = by_name.get("switchyard/stack")
    if fw and ours:
        fa = attribution[fw["variant"]]["step_share_pct"]
        oa = attribution[ours["variant"]]["step_share_pct"]
        w(
            f"\nBlock AttnRes is **{fa:.1f}% of the framework step** and "
            f"**{oa:.1f}% of the fused step**. This is a"
        )
        w(f"{fa / oa:.1f}x reduction in the mechanism's overhead. End to end that is")
        w(f"**{fw['step']['median_ms'] / ours['step']['median_ms']:.2f}x** training throughput,")
        w(f"{fw['step']['median_ms']:.0f} ms down to {ours['step']['median_ms']:.0f} ms, and")
        w(f"**{ours['tokens_per_second'] / fw['tokens_per_second']:.2f}x** the tokens per second.\n")
        w("Quoting the Amdahl arithmetic rather than the kernel speedup is deliberate.")
        w("The operator is only one part of a training step. The end-to-end figure includes")
        w("the rest of the model and is the relevant result here.\n")

    if stack and ours:
        saved = (stack["peak_memory_bytes"] - ours["peak_memory_bytes"]) / 2**30
        w(f"The arena saves **{saved:.2f} GiB** of peak memory against stacking")
        w(f"({stack['peak_memory_bytes'] / 2**30:.2f} to "
          f"{ours['peak_memory_bytes'] / 2**30:.2f} GiB). The paper's pseudocode stacks at")
        w("every site, which at eight blocks copies most of the residual history again")
        w("per sublayer:")
        sc = ours.get("staging_slab_copies")
        st = stack.get("staging_slab_copies")
        if sc and st:
            w(f"{st} slab copies per forward against {sc}, where a slab is one")
            w(f"`B x T x D` tensor ({stack['slab_bytes'] / 2**20:.0f} MiB here).")
        step_overhead = 100 * (ours["step"]["median_ms"] / base["step"]["median_ms"] - 1)
        memory_delta = (ours["peak_memory_bytes"] - base["peak_memory_bytes"]) / 2**30
        memory_percent = 100 * (
            ours["peak_memory_bytes"] / base["peak_memory_bytes"] - 1
        )
        mechanism_share = attribution[ours["variant"]]["step_share_pct"]
        w(
            "\nAgainst the standard-residual control, the fused model adds "
            f"{memory_delta:.2f} GiB of peak"
        )
        w(
            f"memory ({memory_percent:.0f}%) and {step_overhead:.1f}% of step time. "
            f"The residual mechanism is {mechanism_share:.1f}% of the fused step. "
            "These are"
        )
        w("the numbers an architect deciding whether to adopt it would want.\n")

    if any(v.get("source_counts_match_eq6") for v in variants):
        w("The source-count schedule the model actually produces was checked against the")
        w("paper's Eq. 6 at run time, not just in tests.\n")

    smoke = d.get("smoke")
    if smoke:
        w("## Training smoke test\n")
        w("Small config, fp32, overfitting one fixed batch for 300 steps. This is not a")
        w("quality claim; it checks that a systems change did not break learning.\n")
        w("| variant | loss | finite | uniform at init |")
        w("|---|---|---|---|")
        for s in smoke:
            w(f"| {s['residual']} | {s['loss_initial']:.4f} -> {s['loss_final']:.4f} | "
              f"{s['finite']} | {s.get('init_is_uniform', '--')} |")
        a = next((s.get("alpha_summary") for s in smoke if s.get("alpha_summary")), None)
        if a:
            w("\nAll three overfit and none diverges. The AttnRes runs start from exactly")
            w("uniform depth attention, as the zero-initialized pseudo-queries require")
            w(f"(max deviation {smoke[1].get('init_uniform_max_dev', 0):.1e}).\n")
            w("After 300 steps the depth attention has moved but not collapsed: mean")
            w(f"normalized entropy {a['mean_normalized_entropy']:.3f} of `ln N`, mean maximum")
            w(f"weight {a['mean_max_weight']:.3f}, and {a['mean_weight_on_embedding']:.3f} of")
            w("the mass still on the token embedding. That is an observation on a")
            w("deliberately degenerate task, not a finding -- anything more would need")
            w("real training, which is out of scope here.\n")

    ddp_path = REPO / "results" / "ddp.json"
    if ddp_path.exists():
        ddp = json.loads(ddp_path.read_text())
        scaling = ddp.get("scaling", {})
        w("## Two GPUs\n")
        w("Block AttnRes is a local tensor operation; nothing about it needs cross-device")
        w("communication, and inventing some so this section could exist would be")
        w("contrived. So the two-GPU work asks the two questions that are worth asking:")
        w("does the operator still train correctly under DDP, and where does scaling stop")
        w("on a machine whose cards are connected by PCIe at a measured 25.8 GB/s with no")
        w("NVLink.\n")
        w("| variant | 1 GPU tok/s | 2 GPU tok/s | speedup | efficiency |")
        w("|---|---|---|---|---|")
        for name, s in scaling.items():
            w(f"| {name} | {s['one_gpu_tokens_per_s']:.0f} | {s['two_gpu_tokens_per_s']:.0f} | "
              f"{s['speedup']:.2f}x | {100 * s['efficiency']:.0f}% |")
        checks = [
            r["grad_check"]
            for r in ddp.get("dual", {}).get("results", [])
            if r.get("grad_check")
        ]
        if checks and all(
            "max_abs_deviation_from_manual_average" in check
            and check.get("passed") is True
            for check in checks
        ):
            maximum = max(
                check["max_abs_deviation_from_manual_average"] for check in checks
            )
            tolerance = max(check["effective_tolerance"] for check in checks)
            ranks = max(check["validated_rank_count"] for check in checks)
            w("\nThe normal DDP backward matches an explicit average of the local")
            w(f"gradients across {ranks} ranks. The maximum deviation is {maximum:.1e},")
            w(f"and the enforced tolerance is {tolerance:.1e}. The float64-oracle")
            w("operator tests remain the source of truth for local gradient mathematics.\n")
        elif checks:
            w("\nThe stored DDP result uses the old correctness check. Regenerate it")
            w("before release. The revised benchmark compares a normal DDP backward with")
            w("an explicit average of unsynchronized local gradients and fails on a")
            w("mismatch. The float64-oracle operator tests remain the source of truth for")
            w("local gradient mathematics.\n")
        w("Scaling holds up better than the interconnect would suggest -- 85-87% rather")
        w("than the collapse a 25.8 GB/s link and a ~2.6 GB bf16 gradient all-reduce might")
        w("imply -- because NCCL overlaps the reduction with the backward pass. The fused")
        w("variant scales marginally *better* (87% against 85%), which is not a win worth")
        w("claiming: it has slightly more compute per byte communicated, so there is more")
        w("backward to hide the all-reduce behind.\n")

    dest = REPO / "docs" / "model.md"
    dest.write_text("\n".join(out).rstrip() + "\n")
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
