"""Render docs/third_party.md from results/third_party_bfloat16.json."""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
IMPLS = ["speed_of_light", "switchyard", "liger", "fla", "catswe"]
LABEL = {
    "speed_of_light": "ceiling",
    "switchyard": "**switchyard**",
    "liger": "Liger-Kernel",
    "fla": "fla",
    "catswe": "catswe",
}


def main() -> None:
    src = REPO / "results" / "third_party_bfloat16.json"
    data = json.loads(src.read_text())
    rows: dict[tuple, dict] = {}
    for r in data["results"]:
        s = r["shape"]
        rows.setdefault((s["n"], s["b"], s["t"], s["d"]), {})[r["impl"]] = r

    out: list[str] = []
    w = out.append
    env = data.get("environment", {})

    w("# Head-to-head against the existing kernels\n")
    w("Generated by `scripts/summarize_third_party.py` from")
    w("`results/third_party_bfloat16.json`. Reproduce with `scripts/fetch_third_party.sh`")
    w("then `python bench/bench_third_party.py`.\n")
    w(f"{env.get('device_name', 'unknown device')}, bf16, median of 100 CUDA-event-timed")
    w("reps with L2 flushed between them. Every implementation is verified against a")
    w("float64 oracle before it is timed, with each project's RMSNorm gain set to ones,")
    w("logit scale to 1.0 and output RMSNorm disabled so all compute the same function.\n")

    w("## Forward: latency in ms, and achieved GB/s\n")
    hdr = "| shape | " + " | ".join(LABEL[i] for i in IMPLS) + " |"
    w(hdr)
    w("|---" * (len(IMPLS) + 1) + "|")
    for k, im in rows.items():
        cells = []
        for i in IMPLS:
            r = im.get(i)
            if r and "forward" in r and not r.get("skipped"):
                cells.append(f"{r['forward']['median_ms']:.3f} / {r['forward_achieved_gbps']:.0f}")
            else:
                cells.append("--")
        w(f"| N={k[0]} T={k[2]} D={k[3]} | " + " | ".join(cells) + " |")

    w("\nThe forward is a near four-way tie at the memory ceiling. switchyard, fla and")
    w("catswe are all within a few percent of the speed-of-light kernel almost")
    w("everywhere; there is simply nothing left to win. Liger is the outlier, and the")
    w("gap widens with `N` -- 814 GB/s against 1415 at `N=32`.\n")
    w("fla is faster than us at `D=8192` (1542 vs 1260 GB/s) and `D=1024`. Both are")
    w("shapes where our tiled path runs, and it is the weaker of our two.\n")

    w("## Forward + backward: latency in ms\n")
    cols = [i for i in IMPLS if i != "speed_of_light"]
    w("| shape | " + " | ".join(LABEL[i] for i in cols) + " | best |")
    w("|---" * (len(cols) + 2) + "|")
    wins = dict.fromkeys(cols, 0)
    for k, im in rows.items():
        vals = {}
        for i in cols:
            fb = (im.get(i) or {}).get("fwd_bwd", {})
            if "median_ms" in fb:
                vals[i] = fb["median_ms"]
        best = min(vals, key=vals.get) if vals else None
        if best:
            wins[best] += 1
        cells = [
            (f"**{vals[i]:.3f}**" if i == best else f"{vals[i]:.3f}") if i in vals else "--"
            for i in cols
        ]
        w(f"| N={k[0]} T={k[2]} D={k[3]} | " + " | ".join(cells)
          + f" | {LABEL[best].replace('**', '')} |")
    w("")
    w("Wins: " + ", ".join(f"{LABEL[i].replace('**', '')} {n}" for i, n in wins.items()) + ".\n")
    w("switchyard takes most shapes, but **Liger's backward is faster than ours at")
    w("`D >= 4096` and at `N=32`** -- exactly the shapes where our two-kernel tiled")
    w("backward runs instead of the register-resident one. That is a real deficiency")
    w("and it points at the next piece of work, not at a rounding error.\n")

    bq = [b for b in data.get("batched_queries", []) if "forward" in b]
    if bq:
        w("## Batched pseudo-queries\n")
        w("The switchyard resident path reads the source tile once for all queries.")
        w("It returns the output only. catswe also computes merge statistics and supports")
        w("its backward design. These contracts are related, but they are not identical.\n")
        w("| approach | ms |")
        w("|---|---|")
        for b in bq:
            w(f"| {b['impl']} | {b['forward']['median_ms']:.3f} |")
        ours = next((b for b in bq if b["impl"] == "switchyard batched"), None)
        compiled = next((b for b in bq if b["impl"] == "framework compiled batched"), None)
        theirs = next((b for b in bq if "catswe" in b["impl"]), None)
        if ours and theirs:
            ratio = theirs["forward"]["median_ms"] / ours["forward"]["median_ms"]
            w(f"\nThe output-only switchyard path is {ratio:.2f}x faster than catswe here.")
        if ours and compiled:
            ratio = compiled["forward"]["median_ms"] / ours["forward"]["median_ms"]
            w(f"It is {ratio:.2f}x faster than max-autotuned Inductor.")
        w("See `docs/batched_queries.md` for the query-count and shape sweeps.\n")

    w("## Accuracy\n")
    ref = rows.get((9, 1, 4096, 2048), {})
    w("| implementation | relative L2 vs float64 oracle | multiple of the bf16 rounding floor |")
    w("|---|---|---|")
    for i in IMPLS[1:]:
        r = ref.get(i)
        if not r or "correctness" not in r:
            continue
        c = r["correctness"]
        mult = c["rel_l2"] / c["dtype_floor_rel_l2"] if c.get("dtype_floor_rel_l2") else float("nan")
        w(f"| {LABEL[i]} | {c['rel_l2']:.2e} | {mult:.2f}x |")
    w("\nAt N=9 B=1 T=4096 D=2048. switchyard, fla and catswe all sit exactly at the")
    w("floor -- they accumulate in fp32 and round once. Liger is 1.29x, which is still")
    w("fine, but it is a real difference and it grows with `N` (1.43x at `N=32`).\n")

    w("## A harness bug worth recording\n")
    fl = ref.get("fla", {})
    native = fl.get("fwd_bwd", {}).get("median_ms")
    stacked = fl.get("fwd_bwd_stacked_leaf", {}).get("median_ms")
    if native and stacked:
        w("fla takes a *sequence* of sources rather than one stacked tensor, which is how")
        w("a real model holds them: each block representation is produced by a different")
        w("layer. The first version of this benchmark handed it `N` views of a single leaf")
        w("tensor instead, which makes autograd route every gradient back through `N`")
        w("slice-backwards plus an accumulation.\n")
        w("| fla backward at N=9 D=2048 | ms |")
        w("|---|---|")
        w(f"| `N` views of one leaf (wrong) | {stacked:.3f} |")
        w(f"| `N` separate leaves (its actual API) | {native:.3f} |")
        w(f"\nA **{stacked / native:.1f}x** penalty created entirely by the harness. Reported as")
        w("published, it would have made fla look 11x slower than us at `N=9` and 29x at")
        w("`N=32`, when the true figures are 2.7x and 1.5x. Both numbers are kept in the")
        w("JSON because the gap is itself informative: it is the cost of the pointer-table")
        w("API when the sources really do live in one buffer.\n")

    dest = REPO / "docs" / "third_party.md"
    dest.write_text("\n".join(out) + "\n")
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
